export default [
    {
        label: "首页",
        path: "/Main/Home",
        keyword: "Home",
        icon: "el-icon-s-home",
        children: []
    }, {
        label: "线索管理",
        path: "/Main/Edu/Clue/Home",
        keyword: "Clue",
        icon: "el-icon-star-on",
        children: []
    }, {
        label: "学员管理",
        path: "/Main/Edu/Student/Home",
        keyword: "Student",
        icon: "el-icon-user-solid",
        children: []
    }, {
        label: "班级管理",
        path: "/Main/Edu/Class/List",
        keyword: "Clue",
        icon: "el-icon-s-home",
        children: []
    }, {
        label: "课程管理",
        path: "/Main/Edu/Course/List",
        keyword: "Course",
        icon: "el-icon-s-management",
        children: []
    }, {
        label: "课表管理",
        path: "/Main/Edu/TimeTable/List",
        keyword: "TimeTable",
        icon: "el-icon-s-claim",
        children: []
    }, {
        label: "员工管理",
        path: "/Main/Edu/Staff/List",
        keyword: "Staff",
        icon: "el-icon-s-check",
        children: []
    }, {
        label: "教务设置",
        path: "/Main/Edu/Setting/Campus",
        keyword: "Setting",
        icon: "el-icon-s-tools",
        children: []
    }
]